### ISSUE TITLE
Customize timeout

### ISSUE THREAD

**Issue by olivernybroe** [olivernybroe/phpinsights-intellij#15]
The timeout is set to 5 seconds, which in some cases actually isn't enough.

This issue is about changing the timeout in the settings instead.

**Comment by nunomaduro** [comment]
@olivernybroe PHP Insights v2 with the cache optimisations will help on this right?

**Comment by olivernybroe** [comment]
@nunomaduro Yes definitely 👍 But it will still have a problem if the file is too big for initial analysis
