### ISSUE TITLE
[Feat] Add support for setting the configuration file

### ISSUE THREAD

**Issue by olivernybroe** [olivernybroe/phpinsights-intellij#2]
A lot of users has a configuration file, to set what preset they are using and for defining custom rules.
Right now it is not possible to specify which config file is used, which means it's close to unusable. 😟

**Comment by mattfletcher** [comment]
Where will I find this option please?

**Comment by olivernybroe** [comment]
@mattfletcher under `Editor->Inspections->Quality tools`
![image](https://user-images.githubusercontent.com/5870441/65324034-45e46f80-dbab-11e9-8568-e43289f6cb16.png)
