### ISSUE TITLE
com.intellij.execution.process.ProcessNotCreatedException

### ISSUE THREAD

**Issue by ghost** [olivernybroe/phpinsights-intellij#4]
I just noticed the tweet about the extension for phpstorm. I installed it and get the following error message. `com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "{path to the project}\vendor\bin\phpinsights": CreateProcess error=193, %1 is not a valid Win32 application`

After I reinstalled phpstorm completely, I get this one. `com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "{path to the project}\vendor\bin\phpinsights.bat": CreateProcess error=2, The system cannot find the file specified`

It's on Windows 10 1903.

**Comment by olivernybroe** [comment]
How do you normally run `phpinsight` on windows? 
Do you do `php phpinsight`, `phpinsight` or something else?

**Comment by FFDevelopment** [comment]
Normally I run phpinsights in Git Bash or within PhpStorm on Windows. Either I use `php artisan insights -v` or `php artisan insights -v --format=json > phpinsights.json` as command. But at the last one it will be included into an own web based tool.

**Comment by olivernybroe** [comment]
Hmm, Okay.

In the plugin we run the bin file in composer bin called `phpinsights`. This is the same way phpstorm does it when using `phpcs` or `phpmd`. Both of them works by running the bin file directly without prepending php, and when it is on windows, they run the `.bat` file edition of it instead. 
However `phpinsights` do not have a bat file to run it, so we need to create a bat file which works for phpinsights and pr it to the bin folder of the package.

Here are the bat files from [phpmd ](https://github.com/phpmd/phpmd/blob/master/src/bin/phpmd.bat)and [phpcs](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/bin/phpcs.bat).

I also added a issue on phpinsights package about this https://github.com/nunomaduro/phpinsights/issues/266.

**Comment by olivernybroe** [comment]
@FFDevelopment Do you have an auto generated .bat file in your bin folder from composer?
https://github.com/composer/composer/issues/7370

**Comment by rutvij2292** [comment]
For Windows,

Replace phpinsights.bat file in vendoer\bin

@ECHO OFF
setlocal DISABLEDELAYEDEXPANSION
SET BIN_TARGET=%~dp0/../nunomaduro/phpinsights/bin/phpinsights
php "%BIN_TARGET%" %*
